version: "3.7"
services:
  # db:
  #   image: postgres
  #   ports:
  #     - 5435:5432
  #   expose:
  #     - "5435"
  #   volumes:
  #     - data:/data/db
  #   environment:
  #     POSTGRES_USER: "postgres"
  #     POSTGRES_PASSWORD: "password"

  api:
    restart: unless-stopped
    env_file: .env
    build: ./server
    ports:
      - "4000:4000"
    depends_on:
      - db

  client:
    build: ./client
    ports:
      # - "5173:5173" # dev
      - "4173:4173" # prod
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - api

volumes:
  data: {}
